### ISSUE TITLE
premake5.lua

### ISSUE THREAD

**Issue by GirkovArpa** [4silvertooth/sciter-pdf#1]
I ran into this trying to follow the instructions:
```bash
$ ./premake5 win --sciter="C:\Github\sciter-sdk"
bash: ./premake5: No such file or directory
```
Since `premake5.lua` is apparently a Lua script file, I downloaded the Lua binaries and added the first (and smallest) one to my path. None of them were named lua.exe; they are lua54.exe, luac54.exe, and wlua54.exe, but I renamed the first one to lua.exe. I think the 54 refers to the version number.

Anyhow ...
```bash
$ lua ./premake5.lua win --sciter="C:\Github\sciter-sdk"
C:\Program Files\lua\lua.exe: ./premake5.lua:6: attempt to call a nil value (global 'newoption')
stack traceback:
        ./premake5.lua:6: in main chunk
        [C]: in ?
```
I am not sure if this error is because `win` is not a correct value for `[OPTION]`, or if the `[C]` refers to the `C:` in the sciter path I provided, but I wanted to try this out and am not succeeding 😦

**Comment by 4silvertooth** [comment]
You should download premake5 from https://premake.github.io/ and place it besides the premake5.lua. Also `win` isn't a premake5 supported option, the option is actually preferred IDE supported by premake5, try ./premake5.exe --help for supported platforms.  

Edit: I'll elaborate the installation in Readme

**Comment by GirkovArpa** [comment]
I did not realize premake5 is a typical part of a build process, I should have googled it.  I got it to work 🎉

**Comment by 4silvertooth** [comment]
I used premake because sciter-sdk uses that, but cmake would have been good enough for generating both the project.
